### PR TITLE
Migrate to Whonix-16; remove sd-whonix logging tooling

### LINKED ISSUE #637: Make clean or sdw-admin --uninstall does not remove sd-rsyslog.conf in whonix-gw-15
When uninstalling or running `make clean` in a dev environment, at least one file is not removed from the default Qubes-provided whonix-gw-15 template: `/etc/sd-rsyslog.conf`. We should probably do so in https://github.com/freedomofpress/securedrop-workstation/blob/main/dom0/sd-clean-whonix.sls#L14

### LINKED ISSUE #723: rsyslog.service is masked
# Description
rsyslog.service is masked
1. run `make clean`

## Expected

No failures

## Actual

A failure for the task that runs `sudo qubesctl --skip-dom0 --targets whonix-gw-15 state.sls sd-clean-whonix`. For more details, try running `sudo systemctl restart rsyslog` in `whonix-gw-15` and see error:

```
Failed to restart rsyslog.service: Unit rsyslog.service is masked.
```

## Workaround

Run `systemctl unmask rsyslog.service` and then restart rsyslog.

### LINKED ISSUE #727: Update to Whonix 16
A Whonix 16 template has [been available](https://www.qubes-os.org/news/2021/09/30/whonix-16-template-available/) since September 30; Whonix 15 will reach EOL later this month. Accordingly, we should update to Whonix 16 soon.

### PR DESCRIPTION
**Pull request by eloquence**
## Status

Ready for review

## Description of Changes

Fixes #727 
Fixes #723
Fixes #637

- Migrates to `whonix-gw-16` as the base template for `sd-whonix`, as Whonix 15 reaches end-of-life on November 14.
- Removes our custom logging logic for `sd-whonix`. This has proven difficult to maintain as it requires modification of a system-shipped template. It is also of limited value -- users can still examine Whonix logs inside the VM if needed; they just won't be aggregated to the LogVM.
  - Concretely, we cannot maintain this logic without also publishing an `apt{-test}.freedom.press` Bullseye `Release` file, as Whonix 16 moves from Buster to Bullseye.

### Limitations

This does not remove SecureDrop-specific configurations (`securedrop-keyring` and `securedrop-log` packages, apt repo configuration) from the old `whonix-gw-15` template. IMO this is acceptable as this template is deprecated, shows warning upon use, will not be updated by the SecureDrop Workstation updater, and should ideally be removed by the user or a future update.

### Scenario 1: Upgrade from `whonix-15`

1. Provision a `staging` or `dev` environment based on current `main`, _without_ the changes in this PR (the differences between `staging` and `dev` are unlikely to be relevant for this change, though `staging` is generally preferable)
2. Check out this branch in your development VM (e.g., `sd-dev`)
3. Clone and build a new RPM in `dom0` (`make clone`)
4. Remove your currently installed workstation RPM in `dom0` (`sudo dnf remove securedrop-workstation-dom0-config`)
5. Install the freshly built workstation RPM in `dom0` (`sudo dnf install rpm-build/RPMS/noarch/securedrop-workstation-dom0-config-0.5.5-1.fsc25.noarch.rpm`)
6. Run the SecureDrop Workstation updater (`/opt/securedrop/launcher/sdw-launcher.py --skip-delta 0`).
7. - [ ] Observe that updates complete successfully and no errors are logged in `~/.securedrop_launcher/logs/launcher.log` or `~/.securedrop_launcher/logs/launcher-detail.log`
8. - [ ] Observe that the TemplateVM for `sys-whonix` and `sd-whonix` is set to `whonix-gw-16` (e.g., `qvm-prefs <vmname> template` in `dom0`)
9. Fire up `journalctl -f` in `dom0` to observe unusual events in system logs
9. - [ ] Observe that you can successfully log into the SecureDrop Client and that you see no Whonix-related policy violations in system logs
10. Open a terminal in `sd-log`
11. - [ ] Observe that the logs in `~/QubesIncomingLogs` no longer include new entries for `sd-whonix`
12. Open a terminal in `whonix-gw-16`
13. - [ ] Observe that `/etc/apt/sources.list.d` does not contain an entry for any freedom.press repositories
14. - [ ] Observe that `securedrop-log` and `securedrop-keyring` are not installed (`apt-cache policy <packagename>`)

### Scenario 2: Fresh install

1. Remove any existing SecureDrop Workstation installation (`make clean` or `sdw-admin --uninstall`)
2. Check out this branch in your development VM (e.g., `sd-dev`)
3. Build a new RPM and clone it into `dom0` (`make clone`), then configure it with `config.json` and `sd-journalist.sec`
4. Run `make staging`
5. - [ ] Observe that a staging environment is successfully set up
6. - [ ] Observe that the TemplateVM for `sys-whonix` and `sd-whonix` is set to `whonix-gw-16` (e.g., `qvm-prefs <vmname> template` in `dom0`)
7. - [ ] Observe that you can successfully log into the SecureDrop Client
8. Open a terminal in `sd-log`
9. - [ ] Observe that the logs in `~/QubesIncomingLogs` no longer include `sd-whonix`
10. Open a terminal in `whonix-gw-16`
11. - [ ] Observe that `/etc/apt/sources.list.d` does not contain an entry for any freedom.press repositories
12. - [ ] Observe that `securedrop-log` and `securedrop-keyring` are not installed (`apt-cache policy <packagename>`)

### Scenario 3: Uninstall

1. Uninstall the SecureDrop Workstation with `sdw-admin --uninstall`
2. - [ ] Observe no novel errors during the uninstall (please report recurrence of previous issues such as #505 or #620).

## Checklist

- [x] All tests (`make test`) pass in `dom0`
- [x] No documentation updates are required for this PR

### CODE REVIEW

**Comment by eloquence** [comment]
So far I've been able to migrate an existing dev installation to Whonix 16 by running `make dev` with the changes in this PR. App appears to work without issues post-migration.

What I've not tested yet:
- migrating staging or prod
- using the GUI updater for the migration (not sure yet if a full migration run is required)
- ensuring `make clean` / uninstall performs as expected

**Comment by eloquence** [comment]
I tested today:
- [x] `make clean` behavior -- no issues there.
- [x] `make test` - no test failures introduced by this PR
- :x: Automatic migration - this won't work without further changes.

To automatically migrate existing workstations, we have to ensure that `sys-whonix` and `sd-whonix` are not running while attempting to modify the template.

The updater will apply the `dom0` highstate -- that is, all these states: https://github.com/freedomofpress/securedrop-workstation/blob/main/dom0/sd-workstation.top#L6-L21 -- very early, just after updating `dom0` itself:

https://github.com/freedomofpress/securedrop-workstation/blob/main/launcher/sdw_updater_gui/UpdaterApp.py#L188

As part of this highstate run, it will attempt to change the template for `sd-whonix` and `sys-whonix` to `whonix-gw-16`. Those attempts will fail if those VMs are running, which they are likely to be at system start.

Dropping a migration flag (i.e. using our existing migration logic) won't help with that: an `sdw-admin --apply` run fails similarly if you attempt it while the VMs are running, and besides, the `dom0` highstate is applied first.

So, what to do? I would suggest we _do_ use our existing migration logic. If a migration flag is set, we shut down the Whonix VMs (which may require `qvm-kill`) before we apply the `dom0` state, and we boot them back up afterwards. Making it contingent on a migration flag will ensure we don't do it on every update run.

Would appreciate a quick chat about this, but am also happy to plug away at this strategy a bit to see if it actually works as expected. As far as I can tell, this is the _only_ blocker for the migration; after I shut down the Whonix VMs, I was able to migarte an existing installation to Whonix 16 using the graphical updater and the changes in this PR.

**Comment by conorsch** [comment]
@eloquence Looking good! I tacked on a small commit that updates 15 -> 16 in the `securedrop-handle-upgrade` script, which should resolve the problem with VMs not being shut down prior to updating their template settings. I haven't tested locally, but we'll still need to drop a migration flag in order to trigger that logic.

**Comment by eloquence** [comment]
Added a test plan and promoted to ready. Since the Whonix template was already downloaded on my system through regular updates, I also tried removing it to see if it would successfully be _re-downloaded_ and installed. It was. I did not add that to the test plan since it's already quite comprehensive.

**Review by conorsch — APPROVED** [review]

**Pull request merged**
