### PR TITLE
deploy: install `template-from-qubesdb` in base template and `sd-whonix`

### LINKED ISSUE #936: [4.2] Write vm-specific config values to qubesdb
Tracking/discussion. Let's make use of `.vm-config` part of qubesdb (internal to a VM) to store vm-specific configuration. Eventually this will allow us to get rid of config.json.

Upstream documentation:
https://dev.qubes-os.org/projects/core-admin-client/en/latest/manpages/qvm-features.html#vm-config

## Configurable components

| Status | Value | `dom0`[1] | `sd-app` | `sd-gpg` | `sd-log` | `sd-proxy` | `sd-whonix` |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Drafted | `$QUBES_GPG_DOMAIN` | | [`$QUBES_GPG_DOMAIN`](https://github.com/freedomofpress/securedrop-client/blob/520e6a7490ebd0f1580b52e40127cc913c55e646/client/files/sd-app-qubes-gpg-domain.sh)[2] |
| n/a | `config.json:.environment` | →`/etc/apt/sources.list.d/securedrop_workstation.list` |
| Drafted | `config.json:.hidserv.hostname` | | | | | `/home/user/.securedrop_proxy/sd-proxy.yaml`[2] | `/var/lib/tor/keys/app_journalist.auth_private`[3] |
| Drafted | `config.json:.hidserv.key` | | | | | | `/var/lib/tor/keys/app_journalist.auth_private`[3] |
| Drafted | `config.json:.submission_key_fpr` | | `/home/user/.securedrop_client/config.json`[2] |
| n/a | `config.json:.vmsizes.sd_app` | `qvm-volume resize sd-app:private ...` |
| n/a | `config.json:.vmsizes.sd_log` | `qvm-volume resize sd-log:private ...` |
| | `salt://sd/sd-journalist.sec` | | | `/home/user/.gnupg/sd-journalist.sec`[4] |

1. Out of scope of this ticket; just documenting here for completeness.
2. [x] Program reads directly
3. [x] Helper program templates into file contents
4. [x] **Secret:** install directly into domain and remove from `dom0`

**NB.**  Only testable on Qubes 4.2, where QubesDB starts to return `vm-config.*` as `/vm-config/*`.

## Related
- https://github.com/freedomofpress/securedrop-workstation/issues/853

### LINKED ISSUE #1039: provide reusable script for rendering templates from QubesDB variables
## Description

`securedrop-workstation` should provide a reusable script that VMs can use to template configuration files from QubesDB for use by third-party programs.
* Prototype: https://github.com/freedomofpress/securedrop-client/blob/27cc69d7a87c937ff31bae9190b68ee2138525b8/with-qubesdb

## How will this impact [SecureDrop/SecureDrop Workstation users](https://github.com/freedomofpress/securedrop-ux/wiki/Users)?
No user-facing changes.

## How would this affect the SecureDrop Workstation [threat model](https://github.com/freedomofpress/securedrop-workstation/#threat-model)?
Discussed in #936 and #1013.

## User Stories
- #1004
- #1029

### PR DESCRIPTION
**Pull request by cfm**
## Status

Ready for review

## Description of Changes

- Closes #1039 by adapting freedomofpress/securedrop-client@27cc69d into `template-from-qubesdb.py`, which is installed directly into the base template and `sd-whonix` so that it's available without requiring the installation of a separate package.  (This approach is up for debate!)
- Closes #936, of which this is the final non-secret-provisioning part.

### Follow-up work
- #1029
- https://github.com/freedomofpress/securedrop-workstation/blob/a106e93c3e022faa57b55502fb89e30b6b0a8f12/dom0/sd-whonix.sls#L47

## Testing
1. Delete all your `sd-*` VMs so that `sd-{large,small}-bookworm-templates` can be recreated
2. `make clone && make dev`
3. In `sd-whonix`, create and test a template, e.g.:

    ```sh-session
    [gateway user ~] % cat > template <<EOF
    > {"hidserv_hostname": "$SD_HIDSERV_HOSTNAME"}
    > EOF
    [gateway user ~] % template-from-qubesdb template newfile
    ```
4. [ ] `newfile` contains the value of `qubesdb-read /vm-config/SD_HIDSERV_HOSTNAME`.

### If you have made changes to the provisioning logic

- [ ] All tests (`make test`) pass in `dom0`

No tests are required here, but they will be for the "Follow-Up Tasks" listed above.

### If you have added or removed files

- [x] I have updated `MANIFEST.in` and `rpm-build/SPECS/securedrop-workstation-dom0-config.spec`

### CODE REVIEW

**Comment by legoktm** [comment]
> which is installed directly into the base template and sd-whonix so that it's available without requiring the installation of a separate package. (This approach is up for debate!)

Since it's going in a template/VM, I think it should be in a package. Also we'll presumably want a oneshot systemd command to generate the file on VM startup, so that'll also benefit from being packaged?

I think creating a new `securedrop-qubesdb` package would be pretty lightweight (or `securedrop-whonix-config` or ...) if it's just installing one Python file and a systemd service.

**Comment by legoktm** [comment]
The downside is that we'll need to install the `securedrop-keyring` package in the whonix template :/

**Comment by cfm** [comment]
Yes, exactly.  I've been thinking about this mechanism as a concession to the reality that we will want to configure third-party things = things *not* from our packages = things *not* necessarily on top of our base template.  So consider this a straw man for the purpose of testing that hypothesis—let's discuss further.

**Comment by cfm** [comment]
@legoktm have discussed the tradeoff between (a) directly injecting this script (as proposed here) versus (b) packaging it.  The new plan of action is to: 
1. move this script back to `securedrop-client`;
2. package it as `securedrop-qubesdb`; and
3. create a package that depends on `securedrop-qubesdb` for each VM or feature that needs QubesDB configuration (e.g., #1029) to set up a one-shot systemd timer to configure itself using this script.

**Pull request closed without merging**
