### PR TITLE
Set skip_if_unavailable=False in .repo file

### PR DESCRIPTION
**Pull request by rocodes**
## Status

Ready for review

## Description of Changes

Fixes https://github.com/freedomofpress/securedrop-workstation/pull/1023#pullrequestreview-2089387812 : hat tip @deeplow  for originally noticing this 

Changes proposed in this pull request:

* Adjust .repo file to include `skip_if_unavailable=False`

## Testing

- [x] Visual review (see eg mock / sample configs [here](https://github.com/rpm-software-management/mock/blob/main/mock-core-configs/etc/mock/eol/templates/fedora-30.tpl) - this is a standard/recommended configuration)
- [x] CI is green
- [ ] Updater run completes successfully

Optional/bonus points:
- [ ] with repo unreachable, dom0 updates fail

## Deployment

n/a

### If you have made changes to the provisioning logic

- [ ] All tests (`make test`) pass in `dom0`

### If you have added or removed files

- [ ] I have updated `MANIFEST.in` and `rpm-build/SPECS/securedrop-workstation-dom0-config.spec`

### If documentation is required

- [ ] I have opened a PR in the [docs repo](https://github.com/freedomofpress/securedrop-workstation-docs) for these changes, or will do so later
- [ ] I would appreciate help with the documentation

### CODE REVIEW

**Comment by zenmonkeykstop** [comment]
Needs a test  fixed, I'm on it.

**Comment by rocodes** [comment]
ah, thanks for catching the test, appreciated !

**Comment by zenmonkeykstop** [comment]
This breaks the updater in dev currently, as there is no `workstation/dom0/f37` path on yum-test.securedrop.org. There is a suggested workaround in https://github.com/freedomofpress/securedrop-yum-test/pull/57 but we should probably hold off on merge until said workaround or a better solution is in place.

**Comment by zenmonkeykstop** [comment]
Updater working with dummy f37/ in place!

**Pull request merged**
