### PR TITLE
Fixes dom0 updates in GUI updater

### LINKED ISSUE #646: Packages in dom0 are not being updated
Discovered during post-release testing of 0.5.1 today (#643). The graphical updater has stopped running `qubes-dom0-update` as part of its standard logic, so new RPMs, such as 0.5.1, are not being installed automatically. The upstream `qubes-update-gui` tool is unaffected, and continues to work properly.

The problem was introduced in 0.5.0, via the template consolidation PR, specifically this line: https://github.com/freedomofpress/securedrop-workstation/pull/619/files#diff-d0118b9cd7e4fe0ee2bfa80461f1aa3329be6f49d0b29c5874fde88ad7e1e1f0R179

Although the call to `Updater.apply_updates()` properly passes in `dom0` as a target, the generator returned by that function is never iterated over, so the logic in the function never executes. Compare with the call to the same function lower down, where the results are iterated over: https://github.com/freedomofpress/securedrop-workstation/pull/619/files#diff-d0118b9cd7e4fe0ee2bfa80461f1aa3329be6f49d0b29c5874fde88ad7e1e1f0R197-R201

Let's modify that logic to ensure that dom0 packages are updated as a first step. In order for this change to land, we'll need to release a 0.5.2, and once it's available, instruct pilot participants to run `sudo qubes-dom0-update` manually to pull down the latest. Thereafter, a new invocation of the GUI updater will work as expected.

### PR DESCRIPTION
**Pull request by conorsch**
## Status

Ready for review 

## Description of Changes

Fixes #646 

Changes proposed in this pull request:

Actually runs the package updates within dom0, by iterating over the
generator returned by the apply_updates function, ensuring the logic
runs. Revises the progress bar logic a bit, since the apply_updates
function is called twice, with different expectations about how much the
progress bar should increase.

## Testing
Ideally, install 0.5.0 prod (that's n-1 from most current stable release). Then:

1. Clone this branch to dom0
2. `sudo cp -v launcher/sdw_updater_gui/Updater{,App}.py /opt/securedrop/launcher/sdw_updater_gui/`
3. Close the updater GUI window if it is already open, to ensure a fresh start
4. Confirm via `dnf info securedrop-workstation-dom0-config is at 0.5.0, not 0.5.1
5. Confirm via `qvm-ls | grep fedora-32` that fedora-32 is not installed on the system
6. Run `time /opt/securedrop/launcher/sdw-launcher.py --skip-delta 0` and proceed with upgrade
7. Ensure that 0.5.1 RPM is installed
8. Ensure that F32 is installed and set for all `sys-*` VMs
9. Ensure no errors

### If you have made code changes

- [ ] Linter (`make flake8`) passes in the development environment (this box may
      be left unchecked, as `flake8` also runs in CI)

### If you have made changes to the provisioning logic

- [ ] All tests (`make test`) pass in `dom0` of a Qubes install

- [ ] This PR adds/removes files, and includes required updates to the packaging
      logic in `MANIFEST.in` and `rpm-build/SPECS/securedrop-workstation-dom0-config.spec`

### CODE REVIEW

**Review by emkll — COMMENTED** [review]
Changes here look good to me, tested these changes and observed that `dom0` updates are being checked prior to dom0 state being applied, resolving #646 .

Before merging, I suggest we complete test coverage in Updater.py introduced by these changes:

```
----------- coverage: platform linux, python 3.7.3-final-0 -----------
Name                                 Stmts   Miss  Cover   Missing
------------------------------------------------------------------
sdw_notify/Notify.py                    44      0   100%
sdw_updater_gui/Updater.py             272     12    96%   61-66, 73-78, 108, 110
sdw_updater_gui/UpdaterApp.py          139    139     0%   1-219
sdw_updater_gui/UpdaterAppUi.py         95     95     0%   9-125
sdw_updater_gui/UpdaterAppUiQt5.py      84     84     0%   9-114
sdw_updater_gui/strings.py              14     14     0%   1-41
sdw_util/Util.py                        86      0   100%
------------------------------------------------------------------
TOTAL                                  734    344    53%
```

I've opened #649 to improve test coverage for other files.

**Review by emkll — COMMENTED** [review]
Thanks for updating the tests @zenmonkeykstop , tested the updater functionality locally and observed dom0 being updated. The changes here look good to me. Not approving for merge (yet) so that we can bump versions prior to final QA/release

**Review by zenmonkeykstop — DISMISSED** [review]
Test plan passes happily. Approved.

**Comment by conorsch** [comment]
Thanks for testing! I've pushed a version bump 0.5.1 -> 0.5.2, and consider this ready for merge. Have not yet prepared or pushed a sign tag, will do so Monday, as part of pushing out the release.

**Review by emkll — APPROVED** [review]
LGTM

**Comment by conorsch** [comment]
Added tag: https://github.com/freedomofpress/securedrop-workstation/releases/tag/0.5.2, proceeding with merge and build.

**Pull request merged**
