### PR TITLE
Client integration

### LINKED ISSUE #179: Replace pre-alpha workflow with alpha client
Once the following dependencies are met, we should replace the pre-alpha workflow with the alpha client:
- [x] Download and decrypt messages - https://github.com/freedomofpress/securedrop-client/issues/40
- [x] Decrypt downloaded documents - https://github.com/freedomofpress/securedrop-client/issues/66
- [x] View downloaded documents - https://github.com/freedomofpress/securedrop-client/issues/20
- [x] Create updated client package - https://github.com/freedomofpress/securedrop-client/issues/22

Stretch for MVP integration:
~~Replies to sources - https://github.com/freedomofpress/securedrop-client/issues/16~~

We will need the `securedrop-client` package to be updated and delete existing code for the pre-alpha workflow, update the README, etc. 

~~As part of this work, we should convert `sd-journalist` to `sd-proxy` (https://github.com/freedomofpress/securedrop-workstation/issues/138).~~ (let's do as a separate issue)

This will enable us to QA on master with the most important client functionality. Deletion (https://github.com/freedomofpress/securedrop-client/issues/18) can be handled as an iteration.

### PR DESCRIPTION
**Pull request by redshiftzero**
Close #179

Let's do sd-journalist -> sd-proxy rename in a followup

### CODE REVIEW

**Comment by emkll** [comment]
LGTM, rebased on latest master and fixed securedrop-client dependency name.
I am currently experiencing the issue described in https://github.com/freedomofpress/securedrop-debian-packaging/issues/12, but the package is installed and all tests pass.

**Comment by redshiftzero** [comment]
just tested this, working well in sd-svs, confirmed `securedrop-client` is installed  ✅

**Comment by redshiftzero** [comment]
OK on top of the latest debs I can confirm I can sign into a staging server (I hit an error due to a database migration that we forgot in https://github.com/freedomofpress/securedrop-client/pull/114, but I added that in https://github.com/freedomofpress/securedrop-client/pull/129/files which was merged this morning, so tomorrow AM we can do another `securedrop-client` release with this change

**Comment by conorsch** [comment]
Worked for me! That is, I also encountered the app crash _after_ logging in. Error messages were accurate when I provided bad credentials.

**Comment by redshiftzero** [comment]
thanks for adding the docs updates @emkll, they LGTM!

**Comment by redshiftzero** [comment]
good QA 🥇 , let's open a followup ticket to track this, thanks @emkll

**Pull request merged**
