### PR TITLE
Remove stray and unused mimeapps.list

### PR DESCRIPTION
**Pull request by legoktm**
## Status

Ready for review

## Description of Changes

This was originally sd-proxy/mimeapps.list prior to the great salt refactor, but sd-proxy now provisions mime via the workstation-config package and systemd, so it's not used there either.

So this was probably missed when refactoring the MIME stuff and should be safe to deleted as unused.

## Testing

* [ ] Visual review
* [ ] CI passes

## Deployment

Any special considerations for deployment? n/a

### If you have made changes to the provisioning logic

- [ ] All tests (`make test`) pass in `dom0`

### If you have added or removed files

- [ ] I have updated `MANIFEST.in` and `rpm-build/SPECS/securedrop-workstation-dom0-config.spec`
  - not needed AFAICT

### CODE REVIEW

**Comment by cfm** [comment]
Is this not #1006 again?

**Comment by legoktm** [comment]
Yeah...seems like the issue is something related to dbus rather than the xfce config stuff. I've re-opened that.

**Comment by rocodes** [comment]
I don't see sd-proxy mimeapps in https://github.com/freedomofpress/securedrop-client/tree/main/workstation-config, am I missing something?

**Comment by rocodes** [comment]
Well this was a journey

https://github.com/freedomofpress/securedrop-workstation/blob/012e2115572b4f246083e3dd812cd89b7183aedb/tests/test_proxy_vm.py#L12-L17 

Our past selves decided around the time of template consolidation that defaulting to `open-in-dvm` (like sd-app does) was okay for the proxy.  (The proxy's dispvm is sd-viewer). I'm going to leave this open briefly in case anyone has opinions.

**Comment by rocodes** [comment]
Confirmed on my 4.2 setup that sd-proxy's dispvm is `None`, so `open-in-dvm` is fine. approving.

**Review by rocodes — APPROVED** [review]
- [x] CI is green
- [x] visual review was a journey
- [x] lol @ `great salt refactor`

**Pull request merged**
