### PR TITLE
Implements Debian9-based custom templates for all AppVMs

### LINKED ISSUE #131: Achieve persistent configs via custom TemplateVMs
Right now, the `make all` logic used for development creates VMs whose configurations will not persist after a reboot—either of the host or of the guest. Thus the dependency on `make clean` for the `make all` target: every time provisioning logic changes, we must tear down the old configs and instantiate new ones, to ensure changes are applied.

We should instead create _TemplateVMs_ for the machines that require customizations, setting those TemplateVMs as the base for individual AppVMs (e.g. `sd-journalist`). We've already created a custom RPM for a base template including a grsecurity-patched kernel (see [qubes-template-securedrop-workstation](https://github.com/freedomofpress/qubes-template-securedrop-workstation)). That `securedrop-workstation-template` should be used as the first template, from which subsequent app-specific templates will be created.

So the template hierarchy would look like:

```
dom0 # rpm packages & salt configs installed here
└── securedrop-workstation-template # TemplateVM, Debian-based, includes grsecurity-patched kernel
    └── sd-journalist-template # TemplateVM, includes sd-journalist-files for managing feedback & proxy
        └── sd-journalist # AppVM, includes necessary scripts permanently (i.e. survives reboots)
```

Rather than committing to maintaining additional templates created via `qubes-builder` (as with work on [qubes-template-securedrop-workstation](https://github.com/freedomofpress/qubes-template-securedrop-workstation)), we can manage the template relationships via Salt, and update them over time via updates to RPM packages in dom0 that provide the workstation-specific salt configs. Special attention should be paid to forcing applicatoin of the salt-mandated configs; by default, Qubes appears to leave TemplateVMs alone if they've already been created, so as not to break desired user customizations. Liberal use of `--force` flags or similar should resolve.

### PR DESCRIPTION
**Pull request by conorsch**
Converts all the AppVMs to reference a custom TemplateVM caused `sd-workstation-template`, which is cloned from the system `debian-9` TemplateVM. Summary of changes:

* All AppVMs are now based on `<app_vm_name>-template`, with a single exception: `sd-gpg` has no corresponding `sd-gpg-template`, because its customizations are simply a keyring that lives in $HOME, and therefore would not be inherited from the TemplateVM.
* Creates `sd-workstation-template` as a base TemplateVM for use across the multiple AppVM configurations. Does _not_ include much of the hardening documented in #156, we can follow up after these changes are merged.
* Script paths have changed throughout to convert `/usr/local/` to `/usr/` equivalents. Qubes handles `/usr/local/` directories specially, and allows them to be unique per VM.
* Similarly, use of `/home/user/` paths is now discouraged, since AppVMs don't inherit those from TemplateVMs. Wherever possible, appropriate system paths are now used. 
* VM config tests expanded somewhat to confirm new template settings

### Testing
The test plan remains the same as usual:

1. Run `make all` in `dom0` and confirm no errors.
2. Run `make test` in `dom0` and confirm no errors.
3. Run **Qubes Manager** and visually confirm all the `sd-` VMs are running Debian 9 (or Whonix 14, which is itself based on Debian 9). 
4. Confirm you can download and view a test submission. A plaintext submission should be displayed in `gedit` _in a DisposableVM_. 

As usual, 4 is the real clincher here. Without any out-of-band modifications, you should be able to view a plaintext submission. Have not tried other file formats yet; we should write up a test plan to account for those.

Closes #131. Related to #156 and #158.

### CODE REVIEW

**Comment by conorsch** [comment]
Good catch, @emkll! While working on this I discovered that `decrypt-sd-submission` was not ported to Python3 along with the others in #144. We should be able to solve that here.

**Comment by emkll** [comment]
`make clean` target does not clean all workstation related templates likely due to `scripts/list-vms` not matching all the templates. After running `make clean`, the following templates are still available on my machine:
* sd-whonix-template
* sd-svs-template
* sd-svs-disp-template

**Comment by conorsch** [comment]
Both concerns are addressed, @emkll, please have another look. There was a single change required for the Python 3 port (file-writing bytes-vs-strings, standard fare for 2 to 3 porting), and I updated the destroy logic to be hardcoded. In #135 we can make that logic dynamic via tags, let's keep it simple for now.

Confirmed opening plaintext files (in gedit) and images (which opened in Firefox; flagged in #158 for follow-up).

**Comment by conorsch** [comment]
> A note that with these changes, make all took almost 30 minutes in my local testing, which is significantly more than with previous iterations of the provisioning code, and that this doesn't include updates to the templates

Yes, it's taking a long time. Shortly I believe we should omit the "clean" step from `make all`, and instead treat `make all` as a provision action. Testing instructions can still use `make clean && make all`, but treating these machines as a bit more permanent within the dev env will help us make progress as we integrate the packages.

**Pull request merged**
