### PR TITLE
Containerize build and test environment, add some developer tools

### LINKED ISSUE #806: Resolve warnings when we run `make dom0-rpm`
# Description

Resolve warnings when you run `make dom0-rpm`
```
warning: no previously-included files found matching 'scripts/build-dom0-rpm'
warning: no previously-included files found matching 'scripts/clone-to-dom0'
warning: no previously-included files found matching 'scripts/prep-dev'
warning: File listed twice: /usr/share/securedrop-workstation-dom0-config/config.json.example
```

### LINKED ISSUE #849: Containerize build and test environment, use Fedora 32
Playing off of https://github.com/freedomofpress/securedrop-updater/issues/7 but the same applies to this repository:

> Until now, we've been building RPM packages on Debian. That comes with a couple of downsides where trickery has to happen in the `.spec` file and scripts so that everything ends up where it ought to. Instead it'd be better if we used Fedora 32 (or whatever OS _Qubes OS'_ `dom0` uses at the time) to build RPMs as well as run tests.

### PR DESCRIPTION
**Pull request by eaon**
## Description of Changes

* Change build environment to use containers of the package's target OS
  * Use "native" reproducibility macros as much as possible, removing need for custom scripting
  * Install `diffoscope` and `reprotest` from PyPI for minimal OS package requirements in CI and containers
  * Replace `sed` hack for `reprotest` container support with a custom (inert) `setarch` script, allowing seamless upgrades in the future
* Reorganise repo a bit …
  * … to distinguish between `files/` we ship and `scripts/` used for development
  * … move Python dependencies into `requirements/` in their own folder (as is the case in [`securedrop-client`](https://github.com/freedomofpress/securedrop-client/))
* Add `isort`, `bandit` and `shellcheck`, however, there's no generic `make lint`. CI is just running `black` as it did up until now
* Removes launcher from the `/srv/salt/` directory where it hasn't been used since `make clone` was introduced

Fixes #849
Fixes #806

Towards #837

## Testing

- [x] CI is happy :heavy_check_mark: 
- [x] The package built with `make build-rpm` installs as expected and SDW can be set up as expected
- [x] `make dev` and `make clone` still work

On an already-provisioned Workstation, you'll need to manually apply the following patch in `/home/user/securedrop-workstation` before `make clone` will succeed:

```patch
--- a/scripts/clone-to-dom0
+++ b/scripts/clone-to-dom0
@@ -25,7 +25,7 @@ dom0_dev_dir="$HOME/securedrop-workstation"
 # in the subsequent tarball, which is fetched to dom0.
 function build-dom0-rpm() {
     printf "Building RPM on %s ...\n" "${dev_vm}"
-    qvm-run -q "$dev_vm" "make -C $dev_dir dom0-rpm"
+    qvm-run -q "$dev_vm" "make -C $dev_dir build-rpm"
 }
 
 # Call out to target AppVM to create a tarball in dom0
```

- [x] `make test` passes in `dom0`

## Checklist

- [x] I have updated `MANIFEST.in` and `rpm-build/SPECS/securedrop-workstation-dom0-config.spec`
- [x] I would appreciate help with the documentation
  - Though I believe I've covered everything in this repo. `securedrop-dev-docs` would still need a PR

### CODE REVIEW

**Review by cfm — CHANGES_REQUESTED** [review]
This is great, @eaon.  The test plan looks good, with one caveat:

- [x] CI is happy :heavy_check_mark: 
- [x] The package built with `make build-rpm` installs as expected and SDW can be set up as expected
- [ ] `make dev` and `make clone` still work

This required `s/dom0-rpm/build-rpm` in `dom0`'s copy of `scripts/clone-to-dom0` until the first successful `make clone` from this branch, and then `dom0`'s `securedro-workstation` was up to date.  Would you be willing to build in a transitional step? or do you think it's fair to ask developers to manually either (a) make this change or (b) re-bootstrap `securedrop-workstation` into `dom0`?

- [x] `make test` passes in `dom0`

My only other review note:  In general, I favor long rather than short command-line in scripting and automation.  (Though probably this should be a matter of house style rather than my own.)  If you're open to this kind of line-edit, @eaon, I can review that extra commit quickly.

**Comment by eaon** [comment]
> Would you be willing to build in a transitional step? or do you think it's fair to ask developers to manually either (a) make this change or (b) re-bootstrap `securedrop-workstation` into `dom0`?

> My only other review note: In general, I favor long rather than short command-line in scripting and automation. (Though probably this should be a matter of house style rather than my own.) If you're open to this kind of line-edit, @eaon, I can review that extra commit quickly.

**Comment by eaon** [comment]
> Would you be willing to build in a transitional step? or do you think it's fair to ask developers to manually either (a) make this change or (b) re-bootstrap `securedrop-workstation` into `dom0`?

I'm in the latter camp, but flexible if you feel strongly about it - given the very small developer base we have, the vast majority of which is in-house who also wipe systems on the regular, I think this isn't worth the effort.

> My only other review note: In general, I favor long rather than short command-line in scripting and automation. (Though probably this should be a matter of house style rather than my own.) If you're open to this kind of line-edit, @eaon, I can review that extra commit quickly.

Is this referring to cli arguments/options?

**Comment by cfm** [comment]
On Thu, Apr 27, 2023 at 10:26:09AM -0700, eaon wrote:
> > Would you be willing to build in a transitional step? or do you
> > think it's fair to ask developers to manually either (a) make this
> > change or (b) re-bootstrap `securedrop-workstation` into `dom0`?
> 
> I'm in the latter camp, but flexible if you feel strongly about it -
> given the very small developer base we have, the vast majority of
> which is in-house who also wipe systems on the regular, I think this
> isn't worth the effort.

Yes, that makes sense.  In lieu of a transitional step or even a readme
note, then, I've added a note about this to the top of the pull request
so that we can refer people here once this hits "main".


> > My only other review note: In general, I favor long rather than
> > short command-line in scripting and automation. (Though probably
> > this should be a matter of house style rather than my own.) If
> > you're open to this kind of line-edit, @eaon, I can review that
> > extra commit quickly.
> 
> Is this referring to cli arguments/options?

Yes: "apt-get --yes" instead of "apt-get -y", etc.  Not a blocker if you
feel otherwise.

**Comment by eaon** [comment]
While in principle I would agree with you, I took a quick look and most instances in these commits involve `dnf` which has `--assumeyes` for `-y` which I find more cumbersome than helpful, and `pip install` has `--requirement` for `-r` which is unfortunately singular which also makes me rather unhappy. I'd rather keep it as is - which would also mean no porting work for `securedrop-updater` is necessary either. Thank you for the heads up though, it's a good thing to keep in mind in general.

**Review by cfm — APPROVED** [review]
That's persuasive, @eaon.  :-)  Onwards!

**Pull request merged**
